pipeline:
  build:
    image: node:latest
    environment:
      - DEBUG=*
    commands:
      - npm install
      - npm install -g mocha
      - npm install -g istanbul
      - npm install -g gulp
      - npm install -g debug
